/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import AppPackage.AnimationClass;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/**
 *
 * @author Anand
 */
public class Animation extends javax.swing.JFrame {
     AnimationClass AC=new AnimationClass();
    /**
     * Creates new form NewJFrame
     */
    public Animation() {
        initComponents();
        slideshow();
    }
    public void slideshow()
{
    new Thread()
	{	int count=0;
		@Override
		public void run()
		{
			try{
				while(true){
                                    switch(count){
                                    case 0:
                                        ImageIcon I1=new ImageIcon(getClass().getResource("/AnimationImg/animation Pg1.jpg"));
                                        bgslide1.setIcon(I1);
                                        Thread.sleep(5000);
                                            
                                        AC.jLabelXLeft(0,-960,20,8,bgslide1);
                                        AC.jLabelXLeft(960,0,20,8,bgslide2);
                                        count=1;
                                        break;
                                    case 1:
                                        ImageIcon I2=new ImageIcon(getClass().getResource("/AnimationImg/Animation pg2.jpg"));
                                         bgslide2.setIcon(I2);
                                        Thread.sleep(5000);
                                        AC.jLabelXRight(-960,0,20,8,bgslide1);
                                        AC.jLabelXRight(0,960,20,8,bgslide2);
                                        count=2;
                                        break;
                                    case 2:
                                        ImageIcon I3=new ImageIcon(getClass().getResource("/AnimationImg/Animation pg3.jpg"));
                                         bgslide1.setIcon(I3);
                                        Thread.sleep(5000);
                                            
                                        AC.jLabelXLeft(0,-960,20,8,bgslide1);
                                        AC.jLabelXLeft(960,0,20,8,bgslide2);
                                        count=3;
                                        break;
					
                                   case 3:
                                       ImageIcon I4=new ImageIcon(getClass().getResource("/AnimationImg/Animation pg4.jpg"));
                                         bgslide2.setIcon(I4);
                                        Thread.sleep(5000);
                                        AC.jLabelXRight(-960,0,20,8,bgslide1);
                                        AC.jLabelXRight(0,960,20,8,bgslide2);
                                        count=4;
                                        break;
                                   case 4:
                                       ImageIcon I5=new ImageIcon(getClass().getResource("/AnimationImg/Animation pg6.jpg"));
                                         bgslide1.setIcon(I5);
                                        Thread.sleep(12000);
                                        AC.jLabelXLeft(0,-960,20,8,bgslide1);
                                        AC.jLabelXLeft(960,0,20,8,bgslide2);
                                        count=5;
                                        break;
                                   case 5:
                                       ImageIcon I6=new ImageIcon(getClass().getResource("/AnimationImg/Animation pg5.jpg"));
                                         bgslide2.setIcon(I6);
                                        Thread.sleep(5000);
                                        AC.jLabelXRight(-960,0,20,8,bgslide1);
                                        AC.jLabelXRight(0,960,20,8,bgslide2);
                                        count=0;
                                        break;
                                }
					}
		

			}
			catch(Exception  e)
                        { 
                            JOptionPane.showMessageDialog(null, e.getStackTrace());
                        }
		}							
	}.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgslide2 = new javax.swing.JLabel();
        bgslide1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CREDO");
        setIconImage(new ImageIcon(getClass().getResource("/Logos/favicon.png")).getImage()
        );
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(960, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgslide2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnimationImg/Animation pg4.jpg"))); // NOI18N
        getContentPane().add(bgslide2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, -1, 540));

        bgslide1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AnimationImg/animation Pg1.jpg"))); // NOI18N
        bgslide1.setRequestFocusEnabled(false);
        getContentPane().add(bgslide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setForeground(new java.awt.Color(0, 51, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/lock.png"))); // NOI18N
        jLabel1.setText("Login");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 140, 50));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setForeground(new java.awt.Color(0, 51, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/enter.png"))); // NOI18N
        jLabel2.setText("Register");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 190, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 1040, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
       Loginpg l=new Loginpg();
       l.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
       Register r=new Register();
       r.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
                       // Set System L&F
        UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Animation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Animation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Animation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Animation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Animation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgslide1;
    private javax.swing.JLabel bgslide2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
