
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anand
 */
public class Loginpg extends javax.swing.JFrame {

    /**
     * Creates new form Loginpg
     */
    public Loginpg() {
        initComponents();
                this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        un = new javax.swing.JTextField();
        pw = new javax.swing.JPasswordField();
        Login = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        ShowPwdBtn = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setIconImage(new ImageIcon(getClass().getResource("/Logos/favicon.png")).getImage()
        );
        setMinimumSize(new java.awt.Dimension(790, 410));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(960, 540));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 255, 255));
        jLabel2.setText("Login to your account");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 430, 60));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("Phone no.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 255));
        jLabel4.setText("Password");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        un.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        un.setNextFocusableComponent(pw);
        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        jPanel2.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 300, 40));

        pw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pw.setEchoChar('\u25cf');
        pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwActionPerformed(evt);
            }
        });
        jPanel2.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 260, 40));

        Login.setBackground(new java.awt.Color(0, 255, 0));
        Login.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        Login.setForeground(new java.awt.Color(153, 0, 153));
        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel2.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 259, -1));

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setText("Don't have an account?");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        Register.setBackground(new java.awt.Color(0, 255, 0));
        Register.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        Register.setForeground(new java.awt.Color(153, 0, 153));
        Register.setText("Register");
        Register.setToolTipText("Create a new account");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel2.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        ShowPwdBtn.setBackground(new java.awt.Color(255, 255, 255));
        ShowPwdBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/hide.png"))); // NOI18N
        ShowPwdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPwdBtnActionPerformed(evt);
            }
        });
        jPanel2.add(ShowPwdBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 40, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 550, 300));

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 60, 50));

        jLabel6.setForeground(new java.awt.Color(153, 0, 153));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled presentation.jpg"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(960, 500));
        jLabel6.setMinimumSize(new java.awt.Dimension(960, 400));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 970, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Global g=new Global();
    data d=new data();
    
    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
    Customer m=new Customer();
    Seller s=new Seller();
    String  x=un.getText();
    String password=pw.getText();

    try
    { Class.forName("java.sql.Driver");    
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/credo", "root", "root");
     Statement st = con.createStatement();
     String sql="select*from profile where Mobile_No='"+x+"' and password='"+password+"';" ;
     ResultSet rs=st.executeQuery(sql);
     
     if(rs.next()){
         //possible only if that record exists
      String sno=rs.getString(1);
      String fn=rs.getString(2);
      String ln=rs.getString(3);
      String mn=rs.getString(4);
      String ct=rs.getString(5);
      String mail=rs.getString(6);
      String dis=rs.getString(7);    
      String pwd=rs.getString(8);
      String type=rs.getString(9);
         
      
        d.vault(sno,fn,ln,mn,ct,mail,dis,pwd,type);
          //uploads the user data to data class
            
                if(type.equals("Sell"))
                 s.setVisible(true);
                else
                    m.setVisible(true);
            this.dispose();
            
     }
     else{JOptionPane.showMessageDialog(this,"Incorrect password or username");}
     
     rs.close();
     st.close();
     con.close();
 
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null,e.getMessage());
    }
    
    
    }//GEN-LAST:event_LoginActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        // TODO add your handling code here:
        Register x= new Register();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisterActionPerformed

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
       pw.grabFocus();
    }//GEN-LAST:event_unActionPerformed

    private void pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwActionPerformed
       Login.doClick(3);
    }//GEN-LAST:event_pwActionPerformed

    private void ShowPwdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPwdBtnActionPerformed
        if(ShowPwdBtn.isSelected()){
            pw.setEchoChar((char)0);
        ImageIcon I1=new ImageIcon(getClass().getResource("/Logos/eye.png"));
                                        ShowPwdBtn.setIcon(I1);
        }
        else{
            pw.setEchoChar('\u25cf');
        ImageIcon I2=new ImageIcon(getClass().getResource("/Logos/hide.png"));
                                        ShowPwdBtn.setIcon(I2);
        }
    }//GEN-LAST:event_ShowPwdBtnActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
             UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());
                }
            
         catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginpg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginpg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JButton Register;
    private javax.swing.JToggleButton ShowPwdBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField pw;
    private javax.swing.JTextField un;
    // End of variables declaration//GEN-END:variables
}
