import java.awt.Color;
import java.sql.*;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anand
 */
public class Seller extends javax.swing.JFrame {

    /**
     * Creates new form Seller
     */
    public Seller() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        num = new javax.swing.JTextField();
        dist = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pwd1 = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        pwd2 = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        pwd3 = new javax.swing.JPasswordField();
        savepwdbtn = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        agreepanel = new javax.swing.JPanel();
        agreecb = new javax.swing.JCheckBox();
        AgreeBtn = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        prodnTf = new javax.swing.JTextField();
        BuyerNTf = new javax.swing.JTextField();
        QuanTf = new javax.swing.JTextField();
        LocTf = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        emailTf = new javax.swing.JTextField();
        ContactTf = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel31 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        RefreshStocks = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Changeprof = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        Cangepwd = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        cmb1 = new javax.swing.JComboBox<>();
        cmb2 = new javax.swing.JComboBox<>();
        Upload = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        ChkBuyer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jDialog1.setMinimumSize(new java.awt.Dimension(800, 500));
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialog1WindowOpened(evt);
            }
        });
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Name");

        jLabel18.setText("First Name");

        jLabel19.setText("Last name");

        update.setText("Update Profile");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel24.setText("E-mail");

        jLabel25.setText("Phone number");

        jLabel26.setText("District");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dist, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(update)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel18)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel19)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel24)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel25)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel26))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(ln, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(dist, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(update)
                .addContainerGap())
        );

        jDialog1.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 360, 400));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled presentation6.jpg"))); // NOI18N
        jLabel28.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel28FocusGained(evt);
            }
        });
        jDialog1.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 540));

        jDialog2.setMinimumSize(new java.awt.Dimension(400, 400));
        jDialog2.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jDialog2WindowClosing(evt);
            }
        });
        jDialog2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 153));
        jLabel23.setText("Change Password");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel20.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 153));
        jLabel20.setText("Old password");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        jPanel5.add(pwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 170, 30));

        jLabel21.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 153));
        jLabel21.setText("New password");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel5.add(pwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 170, 30));

        jLabel22.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 153));
        jLabel22.setText("Confirm Password");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));
        jPanel5.add(pwd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 170, 30));

        savepwdbtn.setText("Save");
        savepwdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savepwdbtnActionPerformed(evt);
            }
        });
        jPanel5.add(savepwdbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jDialog2.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 340));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled presentation (5).jpg"))); // NOI18N
        jLabel27.setMinimumSize(new java.awt.Dimension(400, 400));
        jLabel27.setPreferredSize(new java.awt.Dimension(400, 400));
        jDialog2.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 380));

        jDialog3.setMinimumSize(new java.awt.Dimension(870, 690));
        jDialog3.setModal(true);
        jDialog3.setResizable(false);
        jDialog3.setSize(new java.awt.Dimension(870, 690));
        jDialog3.setType(java.awt.Window.Type.POPUP);
        jDialog3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agreepanel.setBackground(new java.awt.Color(255, 255, 255));

        agreecb.setText("I agree that I have Communicated with the Buyer and have together come to a mutual decision to perform this deal");
        agreecb.setOpaque(false);

        AgreeBtn.setBackground(new java.awt.Color(0, 51, 255));
        AgreeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/like.png"))); // NOI18N
        AgreeBtn.setText("I Agree");
        AgreeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgreeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agreepanelLayout = new javax.swing.GroupLayout(agreepanel);
        agreepanel.setLayout(agreepanelLayout);
        agreepanelLayout.setHorizontalGroup(
            agreepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agreepanelLayout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addComponent(AgreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(305, 305, 305))
            .addGroup(agreepanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(agreecb, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        agreepanelLayout.setVerticalGroup(
            agreepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agreepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(agreecb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AgreeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDialog3.getContentPane().add(agreepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 870, 120));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jLabel12.setText("Name of Product");

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jLabel14.setText("Name of Buyer");

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jLabel15.setText("Quantity Needed");

        jLabel16.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jLabel16.setText("Location");

        jLabel29.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jLabel29.setText("E-mail");

        jLabel30.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
        jLabel30.setText("Contact");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LocTf, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuanTf, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(52, 52, 52)
                                .addComponent(prodnTf, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(61, 61, 61)
                                .addComponent(BuyerNTf, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(emailTf, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ContactTf, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(prodnTf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(BuyerNTf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(ContactTf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuanTf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LocTf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jDialog3.getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, 290));

        jScrollPane5.setOpaque(false);

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(102, 0, 102));
        jTextPane1.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane1.setText("Contact buyer and share your credentials and preferred mode of transport so that he can pay you the correct amount.\n");
        jScrollPane5.setViewportView(jTextPane1);

        jDialog3.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 880, 120));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/twitter_header_photo_78.jpg"))); // NOI18N
        jDialog3.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 160));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales and upload page");
        setIconImage(new ImageIcon(getClass().getResource("/Logos/favicon.png")).getImage());
        setPreferredSize(new java.awt.Dimension(940, 710));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(153, 255, 153));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null), "Dash Board", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 0, 36), new java.awt.Color(255, 255, 0))); // NOI18N
        jTabbedPane1.setForeground(new java.awt.Color(51, 0, 51));
        jTabbedPane1.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });

        tb1.setBackground(new java.awt.Color(153, 255, 153));
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductNnumber", "Name", "Description", "Category", "Price", "Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb1);

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/rubbish-bin.png"))); // NOI18N
        deleteBtn.setText("Delete Product");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        RefreshStocks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/refresh.png"))); // NOI18N
        RefreshStocks.setText("Refresh");
        RefreshStocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshStocksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(RefreshStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RefreshStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(deleteBtn)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Stocks", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Changeprof.setBackground(new java.awt.Color(102, 102, 255));
        Changeprof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/user.png"))); // NOI18N
        Changeprof.setText("Edit");
        Changeprof.setBorder(null);
        Changeprof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeprofActionPerformed(evt);
            }
        });
        jPanel3.add(Changeprof, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 90, 40));

        LogoutBtn.setBackground(new java.awt.Color(255, 153, 255));
        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/logout.png"))); // NOI18N
        LogoutBtn.setText("Log Out");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        jPanel3.add(LogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 110, 40));

        Cangepwd.setBackground(new java.awt.Color(255, 255, 153));
        Cangepwd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/password.png"))); // NOI18N
        Cangepwd.setText("Change Password");
        Cangepwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CangepwdActionPerformed(evt);
            }
        });
        jPanel3.add(Cangepwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Name");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 50, -1, -1));

        jLabel9.setText("Phone no.");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 97, -1, -1));

        jLabel10.setText("E-mail");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 158, -1, -1));

        jLabel11.setText("District");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 206, -1, -1));
        jPanel6.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 38, 243, 44));
        jPanel6.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 93, 250, 34));
        jPanel6.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 260, 20));
        jPanel6.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 250, 30));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 500, 250));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 480, -1));

        jTabbedPane1.addTab("Profile", jPanel3);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setText("Name of Product");

        jLabel3.setText("Description of product");

        jLabel4.setText("Category");

        jLabel5.setText("Variety");

        jLabel6.setText("Units per");

        jLabel7.setText("Price per Unit");

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });

        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });

        cmb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fruits", "Vegetables", "Diary", "Poultry", "Marine", "Bee Culture", " " }));
        cmb1.setSelectedIndex(-1);
        cmb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb1ActionPerformed(evt);
            }
        });

        cmb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Litres", "mL", "mg", "Piece", "Carton/box", "Tray", "Dozen" }));
        cmb2.setSelectedIndex(-1);
        cmb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb2ActionPerformed(evt);
            }
        });

        Upload.setBackground(new java.awt.Color(153, 255, 153));
        Upload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/upload.png"))); // NOI18N
        Upload.setText("Upload");
        Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadActionPerformed(evt);
            }
        });

        ta1.setColumns(20);
        ta1.setLineWrap(true);
        ta1.setRows(5);
        ta1.setWrapStyleWord(true);
        jScrollPane2.setViewportView(ta1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(49, 49, 49)
                        .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Upload, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2))
                            .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                .addGap(33, 33, 33)
                .addComponent(Upload)
                .addGap(71, 71, 71))
        );

        jTabbedPane1.addTab("Upload product", jPanel2);

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill Number", "Name of Prod.", "Price", "Units", "Quantity", "Name of buyer", "Location", "Customer no."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb2.setGridColor(new java.awt.Color(0, 153, 51));
        tb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb2);

        ChkBuyer.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        ChkBuyer.setForeground(new java.awt.Color(102, 0, 153));
        ChkBuyer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/list.png"))); // NOI18N
        ChkBuyer.setText("Check Buyers");
        ChkBuyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkBuyerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ChkBuyer, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(235, 235, 235))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ChkBuyer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Buyers", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 700, 470));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Untitled presentation (2).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 960, 490));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/twitter_header_photo_78.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 220));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    data d=new data();
    private void ChangeprofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeprofActionPerformed
        jDialog1.setVisible(true);
        jDialog1.setLocationRelativeTo(null);
    }//GEN-LAST:event_ChangeprofActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String Fn=fn.getText();
        String Ln=ln.getText();
        String Num=num.getText();
        String Mail=mail.getText();
        String Dist=dist.getText();
        
           
    
       
        
        
        
        int ans=JOptionPane.showConfirmDialog(this, "Confirm?");
        if(ans==0)
            l1.setText(Fn);
            l2.setText(Num);
            l3.setText(Mail);
            l4.setText(Dist);
            //updates label in profile
        { try{ Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/credo", "root", "root");
        Statement st=con.createStatement();
        String sql="Update profile set first_name='"+Fn+"',last_name='"+Ln+"',email='"+Mail+"',district='"+Dist+"',mobile_no='"+Num+"' where first_name='"+d.first_name+"';";
        st.executeUpdate(sql);
        JOptionPane.showMessageDialog(this, "database updated");
        
        st.close();
        con.close();
        jDialog1.dispose();
        }
        
        catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());}
        
        }
    }//GEN-LAST:event_updateActionPerformed

    private void CangepwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CangepwdActionPerformed
        
        jDialog2.setVisible(true);
        jDialog2.setLocationRelativeTo(null);
    }//GEN-LAST:event_CangepwdActionPerformed

    private void savepwdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savepwdbtnActionPerformed
        String p1=pwd1.getText();
        String p2=pwd2.getText();
        String p3=pwd3.getText();
        JOptionPane.showConfirmDialog(this,"Are you sure? Once the password is changed the previous password can't be used again");
        
      if(p1.equals(d.pwd))  
      { if(p2.equals(p3)){
         try{ Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/credo", "root", "root");
        Statement st=con.createStatement();
        String sql="Update profile set password='"+p2+"' where password='"+p1+"';";
        st.executeUpdate(sql);
        JOptionPane.showMessageDialog(this, "database updated");
        
        st.close();
        con.close();
        jDialog2.dispose();
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());}
        }
        else
            JOptionPane.showMessageDialog(this,"password not matching");
      }else
          JOptionPane.showMessageDialog(this,"Incorrect password");
    }//GEN-LAST:event_savepwdbtnActionPerformed

    private void UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadActionPerformed
       int cato=cmb1.getSelectedIndex(), ex=1;//category
        int uni=cmb2.getSelectedIndex();//unit
    //to check wether form is completed
    if((tf1.getText()).equals(""))
    { tf1.setBackground(java.awt.Color.cyan);
    ex=0;}
    if((ta1.getText()).equals(""))
    { ta1.setBackground(java.awt.Color.cyan);
    ex=0;}
    if((tf3.getText()).equals("")){
     tf3.setBackground(java.awt.Color.cyan);
     ex=0;}
    if((tf4.getText()).equals("")){
     tf4.setBackground(java.awt.Color.cyan); 
     ex=0;}
    
    if((uni==(-1))){
        cmb1.setBackground(java.awt.Color.cyan);
    if(cato==(-1)){
        cmb2.setBackground(java.awt.Color.cyan);
    }
        ex=0;}
    
    
    if(ex==1){
        
    String prod=tf1.getText();
     String desc=ta1.getText();
     String cat=(String)cmb1.getSelectedItem();
     String var=tf3.getText();
     String un=(String)cmb2.getSelectedItem();
     String price=tf4.getText();
     String seller=(d.first_name+" "+d.last_name);
     
     int ans=JOptionPane.showConfirmDialog(this, "Upload product?");
        if(ans==0){
             try{
                   Class.forName("java.sql.Driver");
                   Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/credo", "root", "root");
                   Statement st=con.createStatement();
                   String sql="insert into prod(name,description,category,variety,price,units,seller,profile_no) values('"+prod+"','"+desc+"','"+cat+"','"+var+"','"+price+"','"+un+"','"+seller+"','"+d.Sno+"')";
                  st.executeUpdate(sql);

                  JOptionPane.showMessageDialog(this, "Successfully added the product in the market");
                  {tf1.setText("");
                  ta1.setText("");
                  tf3.setText("");
                  tf4.setText("");
                  cmb1.setSelectedIndex(-1);
                  cmb2.setSelectedIndex(-1);
                  }

                   st.close();
                   con.close();
                           }

                catch(Exception e){
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
    }
    }//GEN-LAST:event_UploadActionPerformed

    private void cmb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb1ActionPerformed

    private void jLabel28FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel28FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28FocusGained

    private void jDialog1WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowOpened
        
      fn.setText(d.first_name);
      ln.setText(d.last_name);
      num.setText(d. mob_no);
      mail.setText(d.mail);
      dist.setText(d.dist);
    
       
                
        
       
    }//GEN-LAST:event_jDialog1WindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
   
        
        l1.setText(d.first_name);
      l2.setText(d.mob_no);
      l3.setText(d.mail);
      l4.setText(d.dist);
      
     
      
      
    }//GEN-LAST:event_formWindowGainedFocus

    private void jDialog2WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog2WindowClosing
        
        
        try{ Class.forName("java.sql.Driver");
        
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/credo", "root", "root");
    
     Statement st = con.createStatement();
     
     String sql="select*from profile where first_name='"+fn+"';" ;
     ResultSet rs=st.executeQuery(sql);
     
     while(rs.next())
     {String sno=rs.getString(1);
      String fn=rs.getString(2);
      String ln=rs.getString(3);
      String mn=rs.getString(4);
      String ct=rs.getString(5);
      String mail=rs.getString(6);
      String dis=rs.getString(7);    
      String pwd=rs.getString(8);
      String type=rs.getString(9);
         
     
          d.vault(sno,fn,ln,mn,ct,mail,dis,pwd,type);
          //uploads the user data to global class
        
     }
      
     rs.close();
     st.close();
     con.close();
    
    }

    catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_jDialog2WindowClosing

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        Loginpg x=new Loginpg();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        DefaultTableModel mod=(DefaultTableModel)tb1.getModel();
          { int row=mod.getRowCount();
                if (row>0)
                {for(int i=0;i<row;i++)
                    mod.removeRow(0);
                }
          }
         try{ Class.forName("java.sql.Driver");
        
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/credo", "root", "root");
    
     Statement st = con.createStatement();
     
     String sql="select*from prod where seller like'%"+d.first_name+"%' ;";
     ResultSet rs=st.executeQuery(sql);
     
     while(rs.next())
     { String fn=rs.getString(1);
      String desc=rs.getString(2);
      String category=rs.getString(3);
      String variety=rs.getString(4);
      String unit=rs.getString(5);
      String price=rs.getString(6);    
      
      
         mod.addRow(new Object[]{fn,desc,category,variety,price,unit});
            
     }
      
     rs.close();
     st.close();
     con.close();
    
    }

    catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_jPanel1FocusGained

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
      DefaultTableModel mod=(DefaultTableModel)tb1.getModel();
      
        int ans=JOptionPane.showConfirmDialog(this,"Are you sure that you want to delete the item from market");
       if(ans==0){
           try{
               Class.forName("java.sql.Driver");
               Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/credo", "root", "root");
               Statement st=con.createStatement();
               String sql="delete from prod where prod_no='"+(String)mod.getValueAt(tb1.getSelectedRow(),0)+"';";
               st.executeUpdate(sql);
               JOptionPane.showMessageDialog(this,"Record deleted");
               
               st.close();
               con.close();
               RefreshStocks.doClick(100);
               
           }
           catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());}
       }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void RefreshStocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshStocksActionPerformed
       DefaultTableModel mod=(DefaultTableModel)tb1.getModel();
          { int row=mod.getRowCount();
                if (row>0)
                {for(int i=0;i<row;i++)
                    mod.removeRow(0);
                }
          }
         try{ Class.forName("java.sql.Driver");
        
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/credo", "root", "root");
    
     Statement st = con.createStatement();
     
     String sql="select*from prod where seller like'%"+d.first_name+"%' ;";
     ResultSet rs=st.executeQuery(sql);
     
     while(rs.next())
     { String fn=rs.getString(1);
      String desc=rs.getString(2);
      String category=rs.getString(3);
      String variety=rs.getString(4);
      String unit=rs.getString("units");
      String price=rs.getString("price");
     
      
         mod.addRow(new Object[]{fn,desc,category,variety,price,unit});
     }
      
     rs.close();
     st.close();
     con.close();
    
    }

    catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_RefreshStocksActionPerformed

    private void tb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb2MouseClicked
    
        
        DefaultTableModel mod=(DefaultTableModel)tb2.getModel();
       
         try{ Class.forName("java.sql.Driver");
        
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/credo", "root", "root");
     Statement st = con.createStatement();
     String sql="select*from profile where Sno="+mod.getValueAt(tb2.getSelectedRow(),7)+" ;";
     ResultSet rs=st.executeQuery(sql);
     
     if(rs.next())
     { String email=rs.getString(5);
      String number=rs.getString(4);
        emailTf.setText(email);
        ContactTf.setText(number);
        prodnTf.setText((String)mod.getValueAt(tb2.getSelectedRow(),1));
        BuyerNTf.setText((String)mod.getValueAt(tb2.getSelectedRow(),5));
        QuanTf.setText((String)mod.getValueAt(tb2.getSelectedRow(),4));
        LocTf.setText((String)mod.getValueAt(tb2.getSelectedRow(),6));
     }
      jDialog3.setVisible(true);
        jDialog3.setLocationRelativeTo(null);  
        
     rs.close();
     st.close();
     con.close();
    
    }

    catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_tb2MouseClicked

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        ta1.grabFocus();
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
       cmb2.grabFocus();
    }//GEN-LAST:event_tf3ActionPerformed

    private void cmb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb2ActionPerformed
       tf4.grabFocus();
    }//GEN-LAST:event_cmb2ActionPerformed

    private void AgreeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgreeBtnActionPerformed
        DefaultTableModel mod=(DefaultTableModel)tb2.getModel();
        if(agreecb.isSelected())
             try{
                   Class.forName("java.sql.Driver");
                   Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/credo", "root", "root");

                   Statement st=con.createStatement();
                   String sql="update trans set status='Agreed' where customer_no="+mod.getValueAt(tb2.getSelectedRow(),7)+" and bill_no="+mod.getValueAt(tb2.getSelectedRow(),0)+" ;";
                  st.executeUpdate(sql);
                  
//                  final String username = "";
//        final String password = "";
//        String body="Hey "+BuyerNTf.getText()+",<br>  "+d.first_name+" "+d.last_name+" has accepted to complete the transaction with you. Please pay your seller the correct amount to avoid any complications. "
//                + "<br>Regards,<br> Team Credo"
//                + "<br><br><hr width=85%><h5 align='right'>Please do not reply to this E-mail</h5>";
//
//        Properties prop = new Properties();
//		prop.put("mail.smtp.host", "smtp.gmail.com");
//        prop.put("mail.smtp.port", "465");
//        prop.put("mail.smtp.auth", "true");
//        prop.put("mail.smtp.socketFactory.port", "465");
//        prop.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
//        
//        Session session = Session.getInstance(prop,
//                new javax.mail.Authenticator() {
//                    @Override
//                    protected PasswordAuthentication getPasswordAuthentication() {
//                        return new PasswordAuthentication(username, password);
//                    }
//                });
//
//        try {
//
//            Message message = new MimeMessage(session);
//            message.setFrom(new InternetAddress(""));
//            message.setRecipients(
//                    Message.RecipientType.TO,
//                    InternetAddress.parse(emailTf.getText())
//            );
//            message.setSubject("Confirmation for consent of transaction");
//            /*message.setText("Dear Mail Crawler,"
//                    + "\n\n Please do not spam my email!");*/
//            message.setContent("<h1 align='center' color='green'>Credo</h1>\n<h3 align='center'>Better Price,Better Life</h3>"+body+"","text/html");
//            Transport.send(message);
//
            JOptionPane.showMessageDialog(this,"Done");
//
//        } catch (MessagingException e) {
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
                  
                    st.close();
                    con.close();
                    jDialog3.dispose();
             }
             catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());}
        else
            agreepanel.setBackground(Color.red);
    }//GEN-LAST:event_AgreeBtnActionPerformed

    private void ChkBuyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkBuyerActionPerformed
        DefaultTableModel mod=(DefaultTableModel)tb2.getModel();
          { int row=mod.getRowCount();
                if (row>0)
                {for(int i=0;i<row;i++)
                    mod.removeRow(0);
                }
          }
         try{ Class.forName("java.sql.Driver");
        
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/credo", "root", "root");
    
     Statement st = con.createStatement();
     
     String sql="select*from trans where seller_name like'%"+d.first_name+"%' and status is null;";
     ResultSet rs=st.executeQuery(sql);
     
     while(rs.next())
     { String cn=rs.getString(9);
      String billno=rs.getString(1);
      String prodn=rs.getString(2);
      String price=rs.getString(3);
      String unit=rs.getString(4);
      String quan=rs.getString(6);
      String loc=rs.getString(7);
       String Customerno=rs.getString(10);   
      
      
         mod.addRow(new Object[]{billno,prodn,price,unit,quan,cn,loc,Customerno});
            
     }
      
     rs.close();
     st.close();
     con.close();
    
    }

    catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_ChkBuyerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
                       // Set System L&F
        UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgreeBtn;
    private javax.swing.JTextField BuyerNTf;
    private javax.swing.JButton Cangepwd;
    private javax.swing.JButton Changeprof;
    private javax.swing.JButton ChkBuyer;
    private javax.swing.JTextField ContactTf;
    private javax.swing.JTextField LocTf;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JTextField QuanTf;
    private javax.swing.JButton RefreshStocks;
    private javax.swing.JButton Upload;
    private javax.swing.JCheckBox agreecb;
    private javax.swing.JPanel agreepanel;
    private javax.swing.JComboBox<String> cmb1;
    private javax.swing.JComboBox<String> cmb2;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField dist;
    private javax.swing.JTextField emailTf;
    private javax.swing.JTextField fn;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField num;
    private javax.swing.JTextField prodnTf;
    private javax.swing.JPasswordField pwd1;
    private javax.swing.JPasswordField pwd2;
    private javax.swing.JPasswordField pwd3;
    private javax.swing.JButton savepwdbtn;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
